### ISSUE TITLE
tag exceptions with releases

### ISSUE THREAD

**Issue by kaystrobach** [networkteam/Networkteam.SentryClient#15]
Implementation needs to be discussed IMHO.

It makes sense to use either the content of a `.release` file generated during deployment containing a release string (either a tag or a commit hash)

Having this would make it easier to track down errors.

PS: Is this project still alive - just seeing the pending PRs

**Comment by christophlehmann** [comment]
Hey Kay,

yes it's still alive ;-)

Your idea sounds good. We can receive the release tag from settings, environment variables and such a release file. What do you think about that fallback order? The release filename itself could be configurable, too.

**Comment by kaystrobach** [comment]
Yes this order is interesting. I think order should be:

- Settings, if really needed
- .release file, maybe there is alteady a standard for that?
- EnvVar

While i prefer the .release file

**Comment by kaystrobach** [comment]
Ahh and latest has highest priority 😉

**Comment by christophlehmann** [comment]
Maybe there are more tags coming, so I suggest to extend the configuration like this

```yaml
Networkteam:
  SentryClient:
    tags:
      release: '%env:RELEASE%'
      # Example usage for file content as tag
      # release: 'FILE:release-file'
```

You make a PR? :-)

**Comment by kaystrobach** [comment]
1. Flow already replaces ENV Vars in Yaml files:
 http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/ResourceManagement.html?highlight=resource%3A

2. FILE: should the standard format for resources in FLOW ...
http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/ResourceManagement.html?highlight=resource%3A#resource-stream-wrapper

So what i would suggest is:

```
Networkteam:
  SentryClient:
    tags:
      release:
        fromFile:
          enable: true / false
          releaseFile: 'resource:// ...' or 'absolutePath' or 'relativePath'
        fromString:
          enable: true / false
          releaseString: 'whatever'
```

**Comment by kaystrobach** [comment]
do you agree?

**Comment by kaystrobach** [comment]
otherwise it could make sense to add it into the backendOptions ... similar to but then the DSN should also be migrated into the backend options ...

```
Neos:
  Flow:
    log:
      systemLogger:
        backend:
          - TYPO3\Flow\Log\Backend\FileBackend

        backendOptions:
          0:
            logFileURL: %FLOW_PATH_DATA%Logs/System.log
            createParentDirectories: TRUE
            severityThreshold: %LOG_INFO%
            maximumLogFileSize: 10485760
            logFilesToKeep: 1
            logMessageOrigin: FALSE
```
